# Generated by Django 3.1.7 on 2021-07-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
