# Generated by Django 3.1.3 on 2021-08-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_auto_20210701_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='Profile pictures/default.png', upload_to='media/Profile pictures'),
        ),
    ]
