# Generated by Django 3.1.3 on 2021-08-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_auto_20210820_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='friend',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
