# Generated by Django 3.1.3 on 2021-08-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0002_auto_20210820_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_image',
            name='accuracy',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='model_image',
            name='symptom',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
