# Generated by Django 3.1.3 on 2021-08-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0003_auto_20210820_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_image',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
