# Generated by Django 3.1.3 on 2021-08-20 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='profile_pictures')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CBC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbc', models.CharField(blank=True, max_length=20, null=True)),
                ('rbc', models.CharField(blank=True, max_length=20, null=True)),
                ('hgb', models.CharField(blank=True, max_length=20, null=True)),
                ('hematocrit', models.CharField(blank=True, max_length=20, null=True)),
                ('platlets', models.CharField(blank=True, max_length=20, null=True)),
                ('polys', models.CharField(blank=True, max_length=20, null=True)),
                ('monocytes', models.CharField(blank=True, max_length=20, null=True)),
                ('eos', models.CharField(blank=True, max_length=20, null=True)),
                ('basos', models.CharField(blank=True, max_length=20, null=True)),
                ('lymphs', models.CharField(blank=True, max_length=20, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
